require('./rectangleTest.js')
require('./circleTest.js')
require('./vectorTest.js')
require('./polygonTest.js')
require('./baseShapeTest.js')
require('./shapeEventEmitterTest.js')
require('./classTest.js')
